
use servicio_clinico;

create table alumno (codigo varchar(4) not null primary key,nombre varchar(50) not null,correo varchar(50) not null,edad int(11) not null,sexo varchar(1) not null,respuestas varchar(30) not null,nivelmadurez varchar(15) not null, eleccionprofesional varchar(15) not null);
insert into alumno(codigo,nombre,correo,edad,sexo,respuestas,nivelmadurez,eleccionprofesional) values("0001","Cristhel","mart_cristhel@gmail.com",17,"F","OAAAAAOOOOAOOAANAAAAAANAAANAOO","Alto","Musica");
insert into alumno(codigo,nombre,correo,edad,sexo,respuestas,nivelmadurez,eleccionprofesional) values("0002","Rebeca","reb_miran@gmail.com",18,"F","ANANNNAANAANNNNNAAAAANNNNNNNNN","Medio","No decidi aun");
insert into alumno(codigo,nombre,correo,edad,sexo,respuestas,nivelmadurez,eleccionprofesional) values("0003","Valeria","avirvar1@gmail.com",17,"F","ONAAANAAAAANNNNAANANAOANNNNNAA","Medio","Finanzas");

create table preguntas(preg1 varchar(200),preg2 varchar(200),preg3 varchar(200),preg4 varchar(200),preg5 varchar(200),preg6 varchar(200),preg7 varchar(200),preg8 varchar(200),preg9 varchar(200),preg10 varchar(200),preg11 varchar(200),preg12 varchar(200),preg13 varchar(200),preg14 varchar(200),preg15 varchar(200),preg16 varchar(200),preg17 varchar(200),preg18 varchar(200),preg19 varchar(200),preg20 varchar(200),preg21 varchar(200),preg22 varchar(200),preg23 varchar(200),preg24 varchar(200),preg25 varchar(200),preg26 varchar(200),preg27 varchar(200),preg28 varchar(200),preg29 varchar(200),preg30 varchar(200));
insert into preguntas(preg1,preg2,preg3,preg4,preg5,preg6,preg7,preg8,preg9,preg10,preg11,preg12,preg13,preg14,preg15,preg16,preg17,preg18,preg19,preg20,preg21,preg22,preg23,preg24,preg25,preg26,preg27,preg28,preg29,preg30) values ("Mis padres saben mejor que nadie lo que yo tengo que estudiar.","Yo pienso escoger la carrera que me recomienden las personas que saben.","Al momento de escoger una carrera uno/a debe tomar en cuenta la profesion que desempenan sus padres.","Cuando llegue el momento yo decidire, ahora no tengo porque pensar en el futuro.","Me cuesta mucho decidir por mi mismo/a, ojala  que hubiera alguien que me dijera lo que debo escoger.","Tengo la impresión de que sirvo para muy pocas cosas.","He preguntado a otras personas para que me aclaren dudas que tengo sobre las carreras.","He leido articulos que hablan sobre las profesiones.","He recibido la ayuda de un orientador, psicologo o profesor en asuntos vocacionales.","He consultado con mis padres acerca de la carrera que me conviene.","He intercambiado con companeros/as o amigos/as acerca de lo que pienso hacer despues de que termine mis estudios.","He solicitado catalogos, programas de estudio, o bien programas de becas a una o mas instituciones. (Contesta De acuerdo únicamente si fuiste tu quien tomo la decision).","Tengo muy poca informacion acerca de las ocupaciones que existen en Bolivia.","El trabajo es una actividad desagradable que tenemos que realizar por obligacion.","Estoy enterado/a de las especializaciones que derivan de mi carrera elegida.","No se cuales son las ocupaciones que estan haciendo mas falta.","Tengo bien claro cuales son mis gustos y mis intereses vocacionales.","Para tener exito en el trabajo hay que olvidar un poco los compromisos familiares y los de amistad.","Para escoger bien hay que pensar en las cosas buenas y malas que tiene cada carrera.","Es mejor no pensar mucho y decidirse de una vez.","Solo hay una profesion adecuada para cada persona.","Ya decidi la carrera que voy a escoger.","He aprendido a tomar desiciones de una forma sistematica y racional.","El temor a fracasar no me deja decidir con tranquilidad.","Tengo dudas acerca de cuales son mis verdaderas habilidades.","Me gustan carreras muy diferentes.","Si una persona no puede estudiar lo que quiere se frustra para toda la vida.","Estoy confuso/a acerca de lo que soy y de lo que debo hacer en el futuro.","He cambiado mucho de opinion con relacion a la carrera que me gusta.","No me gusta ninguna de las carreras que conozco.");

create table profesional(codigo varchar(4) not null primary key,nombre varchar(50) not null,correo varchar(50) not null,contrasena varchar(20) not null);
insert into profesional(codigo,nombre,correo,contrasena) values("1111","Bruno Bustos","samael8496@gmail.com","4901627");
insert into profesional(codigo,nombre,correo,contrasena) values("1112","Daniel Apaza","danielapaza@gmail.com","1234567");
insert into profesional(codigo,nombre,correo,contrasena) values("1113","Juana Melgarejo","melgarejo_juana@gmail.com","7654321");

